name = "id-readtalk"
type = "typescript"
compatibility_date = "2026-03-03"
account_id = "53d61c09062b1ca11788fa763f79313a"

[build]
command = "npm run build"
upload.format = "service-worker"
upload.dir = "dist"

[[bindings]]
type = "service_worker"
name = "OPENAUTH_WORKER"
service = "openauth"
environment = "production"

[[bindings]]
type = "service_worker"
name = "SETTINGS_WORKER"
service = "account"
environment = "production"

[[d1_databases]]
binding = "PAGES_DB"
name = "readtalk_db"
id = "ff653b9c-4e2c-479d-8aa4-497da62de3c5"

[[kv_namespaces]]
binding = "PAGES_KV"
name = "readtalk_kv"
id = "13a468e30cc84fe58ff6297d799050f2"

[[r2_buckets]]
binding = "PAGES_STORAGE"
name = "readtalk-r2"
